### ISSUE TITLE
Server throwing "Error: Can't set headers after they are sent"

### ISSUE THREAD

**Issue by kincaidoneil** [Foo-Bear/bearserver#7]
After every request, I'm receiving this error:

```
frontend ERR: Unhandled rejection Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:346:11)
    at ServerResponse.header (/Users/kincaid/bearserver/node_modules/express/lib/response.js:718:10)
    at ServerResponse.send (/Users/kincaid/bearserver/node_modules/express/lib/response.js:163:12)
    at ServerResponse.json (/Users/kincaid/bearserver/node_modules/express/lib/response.js:249:15)
    at ServerResponse.send (/Users/kincaid/bearserver/node_modules/express/lib/response.js:151:21)
    at /Users/kincaid/bearserver/modules/routes/schedules.js:40:22
    at tryCatcher (/Users/kincaid/bearserver/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/kincaid/bearserver/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/Users/kincaid/bearserver/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/Users/kincaid/bearserver/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Users/kincaid/bearserver/node_modules/bluebird/js/release/promise.js:687:18)
    at Async._drainQueue (/Users/kincaid/bearserver/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/Users/kincaid/bearserver/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues (/Users/kincaid/bearserver/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:570:20)
    at tryOnImmediate (timers.js:550:5)
    at processImmediate [as _immediateCallback] (timers.js:529:5)
```

Which isn't fatal, but I get a similar error that is fatal after I send multiple requests in very quick succession:
```
frontend ERR: /Users/kincaid/bearserver/node_modules/ioredis/node_modules/bluebird/js/main/async.js:43
        fn = function () { throw arg; };
                           ^

Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:346:11)
    at ServerResponse.header (/Users/kincaid/bearserver/node_modules/express/lib/response.js:718:10)
    at ServerResponse.send (/Users/kincaid/bearserver/node_modules/express/lib/response.js:163:12)
    at /Users/kincaid/bearserver/modules/routes/schedules.js:47:20
    at tryCatcher (/Users/kincaid/bearserver/node_modules/ioredis/node_modules/bluebird/js/main/util.js:26:23)
    at Promise.successAdapter (/Users/kincaid/bearserver/node_modules/ioredis/node_modules/bluebird/js/main/nodeify.js:23:30)
    at Promise._settlePromiseAt (/Users/kincaid/bearserver/node_modules/ioredis/node_modules/bluebird/js/main/promise.js:579:21)
    at Promise._settlePromises (/Users/kincaid/bearserver/node_modules/ioredis/node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (/Users/kincaid/bearserver/node_modules/ioredis/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/Users/kincaid/bearserver/node_modules/ioredis/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/Users/kincaid/bearserver/node_modules/ioredis/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:570:20)
    at tryOnImmediate (timers.js:550:5)
    at processImmediate [as _immediateCallback] (timers.js:529:5)
```

I'm using redis 3.2.3 and running `src/redis-server` to start it up. As for the backend, I'm just running `cake build` and then `cake host`.

The errors occur after sending normal GET requests via Postman to `localhost:3000/api/week/2016-09-07`, with no special headers.

Any ideas on what could be causing this?

**Comment by kschamplin19** [comment]
This only happened for `/week`, right? I forgot the closing else statement, so express would always send two responses.

**Comment by kincaidoneil** [comment]
Yes, `/day` doesn't cause the issue.

However, with the fix now `/week` returns `null` for each day (if a {date} parameter was sent)...

**Comment by kschamplin19** [comment]
I'll attach a debugger and see what's going on.

**Comment by kschamplin19** [comment]
It works for me, so any problems are on your end at this point. Check the latest commit, it has some logic revisions that may fix it.

**Comment by kincaidoneil** [comment]
Looks good! Even spamming it with requests works great.
